type Pagamento {
  id: ID!
  pedido: Pedido!
  metodo: String
  status: String
  valor: Float
}

extend type Pedido {
  pagamentos: [Pagamento]
}

extend type Query {
  pagamentos: [Pagamento] @auth(roles: ["RESTAURANTE"])
  pagamento(id: ID!): Pagamento @auth
}

extend type Mutation {
  criarPagamento(pedido_id: ID!, metodo: String, status: String, valor: Float): Pagamento @auth

  editarPagamento(
    id: ID!
    pedido_id: ID
    metodo: String
    status: String
    valor: Float
  ): Pagamento @auth(roles: ["RESTAURANTE"])

  deletarPagamento(id: ID!): Boolean @auth(roles: ["RESTAURANTE"])
}
