# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recomendacao_pb2 as recomendacao__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recomendacao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecomendacaoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObterInsightsLoja = channel.unary_unary(
                '/recomendacao.RecomendacaoService/ObterInsightsLoja',
                request_serializer=recomendacao__pb2.InsightsRequest.SerializeToString,
                response_deserializer=recomendacao__pb2.InsightsResponse.FromString,
                _registered_method=True)
        self.AtualizarAssinatura = channel.unary_unary(
                '/recomendacao.RecomendacaoService/AtualizarAssinatura',
                request_serializer=recomendacao__pb2.AssinaturaRequest.SerializeToString,
                response_deserializer=recomendacao__pb2.AssinaturaResponse.FromString,
                _registered_method=True)


class RecomendacaoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ObterInsightsLoja(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarAssinatura(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecomendacaoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObterInsightsLoja': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterInsightsLoja,
                    request_deserializer=recomendacao__pb2.InsightsRequest.FromString,
                    response_serializer=recomendacao__pb2.InsightsResponse.SerializeToString,
            ),
            'AtualizarAssinatura': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarAssinatura,
                    request_deserializer=recomendacao__pb2.AssinaturaRequest.FromString,
                    response_serializer=recomendacao__pb2.AssinaturaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recomendacao.RecomendacaoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recomendacao.RecomendacaoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecomendacaoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObterInsightsLoja(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recomendacao.RecomendacaoService/ObterInsightsLoja',
            recomendacao__pb2.InsightsRequest.SerializeToString,
            recomendacao__pb2.InsightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarAssinatura(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recomendacao.RecomendacaoService/AtualizarAssinatura',
            recomendacao__pb2.AssinaturaRequest.SerializeToString,
            recomendacao__pb2.AssinaturaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
