type Restaurante {
  id: ID!
  nome: String!
  descricao: String
  endereco: String
  latitude: Float
  longitude: Float
}

extend type Query {
  restaurantes: [Restaurante]
  restaurante(id: ID!): Restaurante
}

extend type Mutation {
  criarRestaurante(
    nome: String!
    descricao: String
    endereco: String
    latitude: Float
    longitude: Float
  ): Restaurante @auth(roles: ["RESTAURANTE"])

  editarRestaurante(
    id: ID!
    nome: String
    descricao: String
    endereco: String
    latitude: Float
    longitude: Float
  ): Restaurante @auth(roles: ["RESTAURANTE"])

  deletarRestaurante(id: ID!): Boolean @auth(roles: ["RESTAURANTE"])
}
