name: express-delivery

services:
  postgres_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_MAIN_USER}
      POSTGRES_PASSWORD: ${DB_MAIN_PASS}
      POSTGRES_DB: ${DB_MAIN_NAME}
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_wal_senders=4", "-c", "max_replication_slots=4"]
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_MAIN_USER} -d ${DB_MAIN_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network


  postgres_entregadores:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_ENTREGADORES_USER}
      POSTGRES_PASSWORD: ${DB_ENTREGADORES_PASS}
      POSTGRES_DB: ${DB_ENTREGADORES_NAME}
    ports:
      - '5434:5432'
    volumes:
      - postgres_entregadores_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_ENTREGADORES_USER} -d ${DB_ENTREGADORES_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    restart: unless-stopped
    networks:
      - app-network

  ms-entregadores:
    build:
      context: .
      dockerfile: ms-entregadores-cs/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      ConnectionStrings__DefaultConnection: Host=postgres_entregadores;Database=${DB_ENTREGADORES_NAME};Username=${DB_ENTREGADORES_USER};Password=${DB_ENTREGADORES_PASS}
      ConnectionStrings__RedisConnection: redis:6379
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: ${RABBIT_USER}
      RabbitMQ__Password: ${RABBIT_PASS}
      RabbitMQ__AutoAssign: "false"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_SERVICE_NAME: ms-entregadores

    depends_on:
      postgres_entregadores:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - '5001:5001'
    restart: unless-stopped
    networks:
      - app-network

  ms-roteamento:
    build:
      context: .
      dockerfile: ms-roteamento-cs/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5002
      OSRM_URL: http://172.25.0.250:5000/
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_SERVICE_NAME: ms-roteamento

    depends_on:
      osrm-server:
        condition: service_started
    ports:
      - '5002:5002'
    restart: unless-stopped
    networks:
      - app-network

  osrm-server:
    image: osrm/osrm-backend
    ports:
      - '5080:5000'
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld /data/${OSRM_FILE}
    restart: unless-stopped
    networks:
      app-network:
        ipv4_address: 172.25.0.250

  api:
    build:
      context: ./api-node
      dockerfile: Dockerfile
    expose:
      - '4000'
    environment:
      DATABASE_URL: postgresql://${DB_MAIN_USER}:${DB_MAIN_PASS}@postgres_db:5432/${DB_MAIN_NAME}?schema=public
      ENTREGADORES_SERVICE_URL: ms-entregadores:5001
      ROTEAMENTO_SERVICE_URL: ms-roteamento:5002
      RECOMENDACAO_SERVICE_URL: ms-recomendacao:50053
      JWT_SECRET: ${JWT_SECRET}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      RABBIT_HOST: rabbitmq
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_SERVICE_NAME: api-node

    depends_on:
      postgres_db:
        condition: service_healthy
      ms-entregadores:
        condition: service_started
      ms-roteamento:
        condition: service_started
      ms-recomendacao:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./api-node:/app
      - /app/node_modules
      - ./protos:/app/protos
    command: sh -c "npm install && npx prisma generate && npx prisma db push --force-reset && npx prisma db seed && npm run dev"
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - api
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    networks:
      - app-network

  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_LOG_LEVEL: notice
      KONG_VAULT_ENV_PREFIX: SECRET_
      SECRET_JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./kong:/usr/local/kong/declarative
    ports:
      - '8000:8000'
    depends_on:
      - api
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  ms-notificacoes:
    build:
      context: .
      dockerfile: ms-notificacoes-py/Dockerfile
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  postgres_recomendacao:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_RECOMENDACAO_USER}
      POSTGRES_PASSWORD: ${DB_RECOMENDACAO_PASS}
      POSTGRES_DB: ${DB_RECOMENDACAO_NAME}
    ports:
      - '5436:5432'
    volumes:
      - postgres_recomendacao_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_RECOMENDACAO_USER} -d ${DB_RECOMENDACAO_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  ms-recomendacao:
    build:
      context: .
      dockerfile: ms-recomendacao-py/Dockerfile
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      DATABASE_URL: postgresql://${DB_RECOMENDACAO_USER}:${DB_RECOMENDACAO_PASS}@postgres_recomendacao:5432/${DB_RECOMENDACAO_NAME}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_SERVICE_NAME: ms-recomendacao

    depends_on:
      postgres_recomendacao:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network


  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      MEM_STORAGE_MAX_TRACES: 10000
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  postgres_data:
  postgres_entregadores_data:
  postgres_recomendacao_data:
