type Usuario {
  id: ID!
  nome: String!
  email: String!
  telefone: String
  latitude: Float
  longitude: Float
  endereco: String
  role: String
  entregador_id: Int
  restaurante_id: Int
}

type LoginResponse {
  token: String!
  usuario: Usuario!
}

extend type Query {
  usuarios: [Usuario]
  usuario(id: ID!): Usuario
  me: Usuario
}

extend type Mutation {
  login(email: String!, senha: String!): LoginResponse

  criarUsuario(
    nome: String!
    email: String!
    telefone: String
    senha: String!
    role: String
    entregador_id: Int
    restaurante_id: Int
  ): Usuario

  editarUsuario(
    id: ID!
    nome: String
    email: String
    telefone: String
    senha: String
    role: String
    entregador_id: Int
    restaurante_id: Int
  ): Usuario

  atualizarEndereco(
    latitude: Float
    longitude: Float
    endereco: String!
  ): Usuario

  deletarUsuario(id: ID!): Boolean
}

