@startuml C4_L1_System_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Diagrama de Contexto de Sistema (L1) - Express Delivery

' -------------------------------------------------------------
' ATORES / PESSOAS
' -------------------------------------------------------------
Person(cliente, "Cliente", "Utiliza o sistema para visualizar cardápios, realizar pedidos e acompanhar entregas em tempo real.")
Person(entregador, "Entregador", "Utiliza o sistema para atualizar sua localização geográfica e gerenciar o status das entregas.")

' -------------------------------------------------------------
' SISTEMA PRINCIPAL
' -------------------------------------------------------------
System(express_delivery, "Sistema Express Delivery", "Permite que clientes peçam comida de restaurantes parceiros e fornece o rastreamento logístico em tempo real com distribuição inteligente de entregadores.")

' -------------------------------------------------------------
' SISTEMAS EXTERNOS / DEPENDÊNCIAS
' -------------------------------------------------------------
System_Ext(osrm_server, "Servidor de Roteamento (OSRM)", "Resolve caminhos geométricos e distâncias ótimas com base nos mapas OpenStreetMap.")

' -------------------------------------------------------------
' RELACIONAMENTOS
' -------------------------------------------------------------
Rel(cliente, express_delivery, "Visualiza cardápios, faz pedidos e acompanha entregas", "HTTPS / JSON")
Rel(entregador, express_delivery, "Envia localização geográfica e atualiza status de entregas", "gRPC / HTTPS")
Rel(express_delivery, osrm_server, "Consulta rotas ideais e estimativas de trajeto", "HTTP / JSON")

@enduml
